---
- name: Deploy System Requirments and Copy Repositories
  hosts: easyremine-app
  user: root
#  become: yes
#  connection: ssh
#  vars:
#   ansible_become_pass: jjksdf$#dchkl*
  roles:
    - role: "../Deployment/repos"
    - role: "../Deployment/system"

- name: Install Nginx And Mariadb
  hosts: easyremine-app
  user: root
  #vars:
  # ansible_become_pass: jjksdf$#dchkl*
  roles:
    - role: "../Deployment/nginx"
    - role: "../Deployment/mariadb"
    - role: "../Deployment/secure_db"

- name: Copy The Templates Files
  hosts: EasyRedmine
  user: easy
  become: yes
  connection: ssh
#  vars:
#   ansible_become_pass: jjksdf$#dchkl*
#   ansible_ssh_port: 22
  roles:
    - role: "../Deployment/temp"

#- name: Copy The Templates Files
#  hosts: webserver
#  user: rootgate
#  become: yes
#  vars:
#    ansible_become_pass: jjksdf$#dchkl*
#  roles:
#    - role: "../Deployment/postfix"

#- name: Configure SSH
#  hosts: webserver
#  user: rootgate
#  become: yes
#  vars:
#    ansible_become_pass: R00tG@teTEaM
#  roles:
#    - role: "../Deployment/ssh_conf"
