---
- name: Deploy System Requirments and Copy Repositories
  hosts: easyremine-app
  user: easy
  become: yes
  connection: ssh
  vars:
   ansible_become_pass: R00tG@teTEaM
  roles:
    - role: "../Deployment/repos"
    - role: "../Deployment/system"

- name: Install Nginx, PHP-FPM And Mariadb
  hosts: webserver
  user: rootgate
  become: yes
  connection: ssh
  vars:
   ansible_become_pass: R00tG@teTEaM
   ansible_ssh_port: 9621
  roles:
    - role: "../Deployment/nginx"
    - role: "../Deployment/php-fpm"
    - role: "../Deployment/mariadb"
    - role: "../Deployment/secure_db"

- name: Copy The Templates Files
  hosts: webserver
  user: rootgate
  become: yes
  connection: ssh
  vars:
   ansible_become_pass: R00tG@teTEaM
   ansible_ssh_port: 9621
  roles:
    - role: "../Deployment/temp"

#- name: Copy The Templates Files
#  hosts: webserver
#  user: rootgate
#  become: yes
#  vars:
#    ansible_become_pass: R00tG@teTEaM
#  roles:
#    - role: "../Deployment/postfix"

#- name: Configure SSH
#  hosts: webserver
#  user: rootgate
#  become: yes
#  vars:
#    ansible_become_pass: R00tG@teTEaM
#  roles:
#    - role: "../Deployment/ssh_conf"

#- name: Install Varnish Server
#  hosts: webserver
#  user: rootgate
#  become: yes
#  vars:
#    ansible_become_pass: R00tG@teTEaM
#  roles:
#    - role: "../Deployment/varnish_server"

#- name: Configure IpTables Security on Varnish Server
#  hosts: webserver
#  user: rootgate
#  become: yes
#  vars:
#    ansible_become_pass: R00tG@teTEaM
#  roles:
#    - role: "../Deployment/iptables"
