---
- name: Copy Mysql Server Configuration file Template
  template: src=server.cnf dest=/etc/my.cnf.d/server.cnf

- name: Copy Database backup Template
  copy: src={{ src_db_backup }} dest={{ dest_db_backup }}

#- name: Extract Website Archive
#  command: chdir=/home/{{ sys_user }}/ /bin/tar xvf public_html.tar.gz

- name: Change ownership and The Permission of WordPress Website
  file: path={{ rootdir }} owner={{ sys_user }} group={{sys_grp }} state=directory recurse=yes

- name: Import Database
  shell: mysql -u {{ mysql_root_username }} -p'{{ mysql_root_password }}' --database {{ db_name }} < {{ db_backup }}

- name: Remove Default Nginx Conf File
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Configure Default Nginx Conf File
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Copy nginx configuration file
  template: src={{ src_ng_conf }} dest={{ dest_ng_conf }}

#- name: Restart Nginx Service
#  service: name=nginx state=restarted enabled=yes

#- name: Restart php-fpm Service
#  service: name=php-fpm state=restarted enabled=yes
