---
- name: Ensure SSHD is running.
  service: name=sshd state=started enabled=yes

- name: Make .SSH Dir to System User
  file: path=/home/rootgate/.ssh/ state=directory owner=root group=root mode=0755

- name: Copy The Keys of rootgate user to connect from secure shell server
  template: src=authorized_keys dest=/home/rootgate/.ssh/authorized_keys owner=root group=root mode=0644

- name: Copy The Configuration File of SSH
  template: src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0600

- name: Restart SSH Service
  service: name=sshd state=restarted

